// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue Nov 17 15:16:19 2020

uart_ip_avalon_interface uart_ip_avalon_interface_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.resetn(resetn_sig) ,	// input  resetn_sig
	.address(address_sig) ,	// input  address_sig
	.writedata(writedata_sig) ,	// input [31:0] writedata_sig
	.readdata(readdata_sig) ,	// output [31:0] readdata_sig
	.write(write_sig) ,	// input  write_sig
	.read(read_sig) ,	// input  read_sig
	.chipselect(chipselect_sig) ,	// input  chipselect_sig
	.waitrequest(waitrequest_sig) ,	// output  waitrequest_sig
	.TX_export(TX_export_sig) ,	// output  TX_export_sig
	.RX_export(RX_export_sig) 	// input  RX_export_sig
);

